# Generated by Django 3.2.8 on 2021-10-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomcode',
            new_name='code',
        ),
    ]
