# Generated by Django 3.2.8 on 2021-10-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_roomcode_room_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.AddField(
            model_name='room',
            name='roomcode',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
